// B1 — Intermediate Representation (IR) schema, validator, and codegen round-trip.
// Pure functions only; safe to import from client or server.
import { z } from "zod";

export const IrThemeSchema = z.object({
  primary: z.string().default("#7c5cff"),
  background: z.string().default("#0b0b14"),
  foreground: z.string().default("#f4f4f8"),
  radius: z.number().min(0).max(32).default(12),
  fontHeading: z.string().default("Inter"),
  fontBody: z.string().default("Inter"),
});

export const IrFieldSchema = z.object({
  name: z.string().min(1).regex(/^[a-z_][a-z0-9_]*$/i),
  type: z.enum(["string", "number", "boolean", "datetime", "json", "uuid", "ref"]),
  required: z.boolean().default(false),
  refModel: z.string().optional(),
  unique: z.boolean().default(false),
});

export const IrModelSchema = z.object({
  name: z.string().min(1).regex(/^[A-Z][A-Za-z0-9]*$/, "PascalCase model name"),
  fields: z.array(IrFieldSchema).min(1),
  rls: z.enum(["owner", "public_read", "members_only", "admin_only"]).default("owner"),
});

export type IrComponent = {
  id: string;
  type: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  props: Record<string, any>;
  children?: IrComponent[];
};
export const IrComponentSchema: z.ZodType<IrComponent> = z.object({
  id: z.string().min(1),
  type: z.string().min(1),
  props: z.record(z.string(), z.any()),
  children: z.array(z.lazy(() => IrComponentSchema)).optional(),
});

export const IrPageSchema = z.object({
  route: z.string().regex(/^\/[a-zA-Z0-9/_:.\-$]*$/, "Route must start with /"),
  title: z.string().min(1),
  description: z.string().default(""),
  auth: z.enum(["public", "authenticated", "admin"]).default("public"),
  layout: z.enum(["default", "fullscreen", "split", "centered"]).default("default"),
  components: z.array(IrComponentSchema).default([]),
});

export const IrIntegrationSchema = z.object({
  kind: z.enum(["auth", "db", "storage", "functions", "ai", "payments", "email", "push", "analytics"]),
  provider: z.string().min(1),
  config: z.record(z.string(), z.any()).default({}),
});

export const IrSchema = z.object({
  version: z.literal(1).default(1),
  name: z.string().min(1).max(80),
  description: z.string().default(""),
  theme: IrThemeSchema.default({}),
  pages: z.array(IrPageSchema).default([]),
  models: z.array(IrModelSchema).default([]),
  integrations: z.array(IrIntegrationSchema).default([]),
  i18n: z.object({
    defaultLocale: z.string().default("en"),
    locales: z.array(z.string()).default(["en"]),
  }).default({}),
});

export type Ir = z.infer<typeof IrSchema>;
export type IrPage = z.infer<typeof IrPageSchema>;
export type IrModel = z.infer<typeof IrModelSchema>;

export const EMPTY_IR: Ir = IrSchema.parse({ name: "Untitled Project" });

// Deterministic hash (FNV-1a 64 → hex) — same IR ⇒ same hash, runs anywhere.
export function hashIr(ir: Ir): string {
  const json = stableStringify(ir);
  let h1 = 0x811c9dc5 | 0;
  let h2 = 0xcbf29ce4 | 0;
  for (let i = 0; i < json.length; i++) {
    const c = json.charCodeAt(i);
    h1 ^= c; h1 = Math.imul(h1, 0x01000193);
    h2 ^= (c << 1) | (c >>> 31); h2 = Math.imul(h2, 0x100000001b3 & 0xffffffff);
  }
  return (h1 >>> 0).toString(16).padStart(8, "0") + (h2 >>> 0).toString(16).padStart(8, "0");
}

function stableStringify(v: unknown): string {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(stableStringify).join(",") + "]";
  const obj = v as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  return "{" + keys.map((k) => JSON.stringify(k) + ":" + stableStringify(obj[k])).join(",") + "}";
}

// ---- IR → files (deterministic web codegen, subset) ----
export type GeneratedFile = { path: string; content: string };

export function generateFilesFromIr(ir: Ir): GeneratedFile[] {
  const out: GeneratedFile[] = [];
  out.push({ path: "foundry.config.json", content: JSON.stringify({ name: ir.name, version: ir.version, integrations: ir.integrations }, null, 2) + "\n" });
  out.push({ path: "src/theme.css", content: themeCss(ir) });
  out.push({ path: "src/ir.json", content: JSON.stringify(ir, null, 2) + "\n" });
  for (const page of ir.pages) out.push({ path: routeToFile(page.route), content: pageTsx(page) });
  for (const m of ir.models) out.push({ path: `db/models/${m.name}.sql`, content: modelSql(m) });
  out.push({ path: "README.md", content: readme(ir) });
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

function routeToFile(route: string): string {
  const trimmed = route.replace(/^\//, "") || "index";
  const parts = trimmed.split("/").map((p) => p.startsWith(":") ? `$${p.slice(1)}` : p);
  return `src/routes/${parts.join(".")}.tsx`;
}

function pageTsx(p: IrPage): string {
  const blocks = p.components.map((c) => `      <Block kind=${JSON.stringify(c.type)} props={${JSON.stringify(c.props)}} />`).join("\n");
  return `// AUTO-GENERATED by Foundry IR codegen. Do not edit by hand.
import { createFileRoute } from "@tanstack/react-router";
import { Block } from "@/lib/runtime/blocks";

export const Route = createFileRoute(${JSON.stringify(p.route)})({
  head: () => ({ meta: [{ title: ${JSON.stringify(p.title)} }, { name: "description", content: ${JSON.stringify(p.description)} }] }),
  component: Page,
});

function Page() {
  return (
    <main data-layout=${JSON.stringify(p.layout)} data-auth=${JSON.stringify(p.auth)}>
${blocks || "      {/* no components */}"}
    </main>
  );
}
`;
}

function modelSql(m: IrModel): string {
  const cols = m.fields.map((f) => `  ${f.name} ${sqlType(f.type)}${f.required ? " NOT NULL" : ""}${f.unique ? " UNIQUE" : ""}`).join(",\n");
  return `-- AUTO-GENERATED
CREATE TABLE IF NOT EXISTS public.${m.name.toLowerCase()} (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
${cols},
  created_at timestamptz NOT NULL DEFAULT now()
);
`;
}

function sqlType(t: string): string {
  switch (t) {
    case "string": return "text";
    case "number": return "numeric";
    case "boolean": return "boolean";
    case "datetime": return "timestamptz";
    case "uuid": return "uuid";
    case "ref": return "uuid";
    default: return "jsonb";
  }
}

function themeCss(ir: Ir): string {
  const t = ir.theme;
  return `:root {
  --primary: ${t.primary};
  --background: ${t.background};
  --foreground: ${t.foreground};
  --radius: ${t.radius}px;
  --font-heading: ${JSON.stringify(t.fontHeading)};
  --font-body: ${JSON.stringify(t.fontBody)};
}
`;
}

function readme(ir: Ir): string {
  return `# ${ir.name}\n\n${ir.description}\n\nGenerated by Foundry. ${ir.pages.length} pages, ${ir.models.length} models, ${ir.integrations.length} integrations.\n`;
}

// ---- IR validation summary used by the Critic loop ----
export type IrIssue = { path: string; message: string; severity: "error" | "warn" };

export function lintIr(ir: Ir): IrIssue[] {
  const issues: IrIssue[] = [];
  const routes = new Set<string>();
  for (const [i, p] of ir.pages.entries()) {
    if (routes.has(p.route)) issues.push({ path: `pages[${i}].route`, message: `Duplicate route ${p.route}`, severity: "error" });
    routes.add(p.route);
  }
  if (!ir.pages.some((p) => p.route === "/")) issues.push({ path: "pages", message: "Missing home route '/'", severity: "warn" });
  const modelNames = new Set<string>();
  for (const [i, m] of ir.models.entries()) {
    if (modelNames.has(m.name)) issues.push({ path: `models[${i}].name`, message: `Duplicate model ${m.name}`, severity: "error" });
    modelNames.add(m.name);
    for (const [j, f] of m.fields.entries()) {
      if (f.type === "ref" && !f.refModel) issues.push({ path: `models[${i}].fields[${j}]`, message: `Ref field ${f.name} missing refModel`, severity: "error" });
      if (f.type === "ref" && f.refModel && !ir.models.find((mm) => mm.name === f.refModel)) {
        issues.push({ path: `models[${i}].fields[${j}]`, message: `Unknown refModel ${f.refModel}`, severity: "error" });
      }
    }
  }
  return issues;
}
