// C3-C5 — Vendor-neutral runtime contract generator for generated apps.
// Pure and deterministic: adapter configs in, portable @app/runtime scaffolding out.
import type { RuntimeAdapterCategory } from "./runtime-adapters.shared";

export type RuntimeContractAdapter = {
  category: RuntimeAdapterCategory;
  provider: string;
  display_name: string;
  status: string;
  capabilities: string[];
  config: Record<string, unknown>;
  secret_refs: string[];
  score: number;
};

export type RuntimeContractFile = { path: string; content: string; language: "ts" | "json" | "md" };

const REQUIRED_CATEGORIES: RuntimeAdapterCategory[] = ["auth", "database", "storage", "functions", "ai", "payments", "email", "push"];

export function runtimeContractSummary(configs: RuntimeContractAdapter[]) {
  const byCategory = new Map(configs.map((config) => [config.category, config]));
  const missingCategories = REQUIRED_CATEGORIES.filter((category) => !byCategory.has(category));
  const degraded = configs.filter((config) => !["healthy", "configured"].includes(config.status));
  const missingSecrets = configs.flatMap((config) =>
    (config.secret_refs ?? []).map((secret) => ({ category: config.category, provider: config.provider, secret })),
  );
  const averageScore = configs.length ? Math.round(configs.reduce((sum, config) => sum + (config.score ?? 0), 0) / configs.length) : 0;
  return {
    requiredCategories: REQUIRED_CATEGORIES,
    configuredCategories: configs.map((config) => config.category).sort(),
    missingCategories,
    degraded: degraded.map((config) => ({ category: config.category, provider: config.provider, status: config.status })),
    missingSecrets,
    averageScore,
    productionReady: missingCategories.length === 0 && degraded.length === 0,
  };
}

export function generateRuntimeContractFiles(projectName: string, configs: RuntimeContractAdapter[]): RuntimeContractFile[] {
  const sorted = [...configs].sort((a, b) => a.category.localeCompare(b.category));
  const manifest = {
    project: projectName,
    generatedAt: "deterministic",
    contractVersion: 1,
    adapters: sorted.map((config) => ({
      category: config.category,
      provider: config.provider,
      displayName: config.display_name,
      status: config.status,
      capabilities: [...(config.capabilities ?? [])].sort(),
      config: redactRuntimeConfig(config.config ?? {}),
      secretRefs: [...(config.secret_refs ?? [])].sort(),
      score: config.score,
    })),
    summary: runtimeContractSummary(sorted),
  };

  return [
    { path: "packages/runtime/foundry.adapters.json", language: "json", content: stableJson(manifest) + "\n" },
    { path: "packages/runtime/src/index.ts", language: "ts", content: runtimeIndexTs(sorted) },
    { path: "packages/runtime/src/providers.ts", language: "ts", content: runtimeProvidersTs(sorted) },
    { path: "packages/runtime/README.md", language: "md", content: runtimeReadme(projectName, sorted) },
  ];
}

function redactRuntimeConfig(config: Record<string, unknown>) {
  return Object.fromEntries(
    Object.entries(config).map(([key, value]) => [
      key,
      /secret|token|key|password|private/i.test(key) ? "<secret-ref>" : value,
    ]),
  );
}

function runtimeIndexTs(configs: RuntimeContractAdapter[]) {
  const categories = REQUIRED_CATEGORIES.filter((category) => configs.some((config) => config.category === category));
  return `// AUTO-GENERATED by Foundry Runtime Contract. Do not edit by hand.
import { resolveRuntimeProvider } from "./providers";

export type RuntimeUser = { id: string; email?: string | null; name?: string | null };
export type RuntimeQuery<T = Record<string, unknown>> = { table: string; where?: Partial<T>; limit?: number };
export type RuntimeFileRef = { bucket: string; path: string; contentType?: string };
export type RuntimeFunctionEvent = { name: string; payload: Record<string, unknown>; user?: RuntimeUser | null };
export type RuntimeAiRequest = { model?: string; messages: Array<{ role: "system" | "user" | "assistant"; content: string }>; temperature?: number };
export type RuntimePaymentRequest = { customerId?: string; priceId: string; quantity?: number; successUrl?: string; cancelUrl?: string };
export type RuntimeEmailRequest = { to: string; subject: string; template: string; data?: Record<string, unknown> };
export type RuntimePushRequest = { userId?: string; segment?: string; title: string; body: string; data?: Record<string, unknown> };

export const runtime = {
${categories.map((category) => `  ${category === "database" ? "db" : category}: resolveRuntimeProvider(${JSON.stringify(category)}),`).join("\n")}
};

export const auth = runtime.auth;
export const db = runtime.db;
export const storage = runtime.storage;
export const fn = runtime.functions;
export const ai = runtime.ai;
export const pay = runtime.payments;
export const mail = runtime.email;
export const push = runtime.push;
`;
}

function runtimeProvidersTs(configs: RuntimeContractAdapter[]) {
  const registry = Object.fromEntries(configs.map((config) => [config.category, {
    provider: config.provider,
    status: config.status,
    capabilities: config.capabilities,
    secretRefs: config.secret_refs,
  }]));
  return `// AUTO-GENERATED by Foundry Runtime Contract. Do not edit by hand.
export type RuntimeCategory = "auth" | "database" | "storage" | "functions" | "ai" | "payments" | "email" | "push";

export const runtimeAdapterRegistry = ${stableJson(registry)} as const;

export function resolveRuntimeProvider(category: RuntimeCategory) {
  const adapter = runtimeAdapterRegistry[category];
  if (!adapter) throw new Error(\`Runtime adapter not configured: \${category}\`);
  return {
    category,
    provider: adapter.provider,
    status: adapter.status,
    capabilities: adapter.capabilities,
    async execute(operation: string, input: Record<string, unknown> = {}) {
      return { ok: true, category, provider: adapter.provider, operation, input };
    },
  };
}
`;
}

function runtimeReadme(projectName: string, configs: RuntimeContractAdapter[]) {
  const rows = configs
    .map((config) => `| ${config.category} | ${config.display_name} | ${config.status} | ${config.capabilities.slice(0, 5).join(", ")} |`)
    .join("\n");
  return `# ${projectName} Runtime Contract

Generated apps import backend services from \`@app/runtime\` instead of vendor SDKs. This keeps auth, database, storage, functions, and AI portable across managed cloud, third-party platforms, and self-hosted infrastructure.

| Category | Provider | Status | Capabilities |
|---|---|---|---|
${rows || "| none | not configured | planned | - |"}
`;
}

function stableJson(value: unknown): string {
  return JSON.stringify(sortDeep(value), null, 2);
}

function sortDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, nested]) => [key, sortDeep(nested)]));
}